module.exports = Object.freeze({
  UPDATE_SETTINGS: 'VIZALITY_SETTINGS_UPDATE',
  TOGGLE_SETTING: 'VIZALITY_SETTING_TOGGLE',
  UPDATE_SETTING: 'VIZALITY_SETTING_UPDATE',
  DELETE_SETTING: 'VIZALITY_SETTING_DELETE'
});
